### ISSUE TITLE
TestError on AArch64 :test_issue14 (module.tests.mkl_pardiso_test.mkl_pardiso_tests

### ISSUE THREAD

**Issue by fubingting** [oxfordcontrol/osqp-python#55]
**_When I execute python setup.py test on aarch64, the error is as follows，Does osqp-python support aarch64?_**
test_issue14 (module.tests.mkl_pardiso_test.mkl_pardiso_tests) ... ERROR in lh_load_lib: Error while loading dynamic library libmkl_rt.so: libmkl_rt.so: cannot open shaect file: No such file or directory
ERROR in osqp_setup: Linear system solver not available.
Tried to obtain it from shared library.
ERROR
test_multithread (module.tests.multithread_test.multithread_tests) ... /home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/python-3.8.8-l73kggq3ezxridinxkfckv4ddztul6python3.8/multiprocessing/pool.py:265: ResourceWarning: unclosed running multiprocessing pool <multiprocessing.pool.ThreadPool state=RUN pool_size=2>
  _warn(f"unclosed running multiprocessing pool {self!r}",
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_nan (module.tests.non_convex_test.non_convex_tests) ... ok
test_non_convex_big_sigma (module.tests.non_convex_test.non_convex_tests) ... ok
test_non_convex_small_sigma (module.tests.non_convex_test.non_convex_tests) ... ERROR in LDL_factor: Error in KKT matrix LDL factorization when computing the nonzero el The problem seems to be non-convex
ERROR in osqp_setup: KKT matrix factorization.
The problem seems to be non-convex.
ok
test_polish_random (module.tests.polishing_test.polish_tests) ... ok
test_polish_simple (module.tests.polishing_test.polish_tests) ... ok
test_polish_unconstrained (module.tests.polishing_test.polish_tests) ... ok
test_primal_and_dual_infeasible_problem (module.tests.primal_infeasibility_test.primal_infeasibility_tests) ... ok
test_primal_infeasible_problem (module.tests.primal_infeasibility_test.primal_infeasibility_tests) ... ok
test_unconstrained_problem (module.tests.unconstrained_test.unconstrained_tests) ... ok
test_solve (module.tests.update_matrices_test.update_matrices_tests) ... ok
test_update_A (module.tests.update_matrices_test.update_matrices_tests) ... ok
test_update_A_allind (module.tests.update_matrices_test.update_matrices_tests) ... ok
test_update_P (module.tests.update_matrices_test.update_matrices_tests) ... ok
test_update_P_A_allind (module.tests.update_matrices_test.update_matrices_tests) ... ok
test_update_P_A_indA (module.tests.update_matrices_test.update_matrices_tests) ... ok
test_update_P_A_indP (module.tests.update_matrices_test.update_matrices_tests) ... ok
test_update_P_A_indP_indA (module.tests.update_matrices_test.update_matrices_tests) ... ok
test_update_P_allind (module.tests.update_matrices_test.update_matrices_tests) ... ok
test_warm_start (module.tests.warm_start_test.warm_start_tests) ... ok

======================================================================
ERROR: test_issue14 (module.tests.mkl_pardiso_test.mkl_pardiso_tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/root/spack-stage/spack-stage-py-osqp-0.6.2-xecbyow6iiudqrypuq75vqgye7jzruch/spack-src/module/tests/mkl_pardiso_test.py", line 25, in test_issue14
    m.setup(self.P, self.q, self.A, self.l, self.u,
  File "/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.3.1/py-osqp-0.6.2-xecbyow6iiudqrypuq75vqgye7jzruch/lib/python3.8/site-packages/osqp/interface.py", line 37, in
    self._model.setup(*unpacked_data, **settings)
ValueError: Workspace allocation error!

----------------------------------------------------------------------
Ran 53 tests in 24.555s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=53 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=53 errors=1 failures=0>

**Comment by goulart-paul** [comment]
You don't have MKL on your platform, so compile with `-DENABLE_MKL_PARDISO=FALSE`.
